"""добавлен ip_address и user_agent к таблице Сессий

Revision ID: acd34158ba6c
Revises: b5b3870913ee
Create Date: 2026-06-12 09:59:49.431771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd34158ba6c'
down_revision: Union[str, Sequence[str], None] = 'b5b3870913ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('sessions', sa.Column('user_agent', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'user_agent')
    op.drop_column('sessions', 'ip_address')
    # ### end Alembic commands ###
