"""initial migration

Revision ID: c3fe0eb7c47c
Revises: 
Create Date: 2026-05-24 11:24:14.055973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3fe0eb7c47c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stock_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('stock_quantity >= 0', name='check_stock_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('loyalty_tiers',
    sa.Column('tier_name', sa.String(length=20), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('points_multiplier', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('min_points_for_tier', sa.Integer(), nullable=False),
    sa.CheckConstraint("tier_name != ''", name='check_tier_name_not_empty'),
    sa.CheckConstraint('discount_percent >= 0 AND discount_percent <= 100', name='check_discount_percent_positive'),
    sa.PrimaryKeyConstraint('tier_name')
    )
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.CheckConstraint('base_price > 0', name='check_base_price_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='check_day_of_week_range'),
    sa.CheckConstraint('multiplier >= 0.5', name='check_multiplier_positive'),
    sa.CheckConstraint('start_time < end_time', name='check_start_end'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pricing_time', 'pricing_rules', ['day_of_week', 'start_time', 'end_time'], unique=False)
    op.create_table('loyalty_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.CheckConstraint('points_balance >= 0', name='check_points_balance_positive'),
    sa.ForeignKeyConstraint(['tier'], ['loyalty_tiers.tier_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('menu_item_id', 'ingredient_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_applied', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('new', 'confirmed', 'preparing', 'completed', 'cancelled')", name='check_status_valid'),
    sa.ForeignKeyConstraint(['card_id'], ['loyalty_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('item_price_at_time', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name='check_quantity_valid'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'menu_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    op.drop_table('recipes')
    op.drop_table('loyalty_cards')
    op.drop_index('idx_pricing_time', table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_table('menu_items')
    op.drop_table('loyalty_tiers')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
