"""Add totp_secret_pending

Revision ID: cef55aa15ef2
Revises: c4f1b2700859
Create Date: 2026-06-12 12:10:42.852971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef55aa15ef2'
down_revision: Union[str, Sequence[str], None] = 'c4f1b2700859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret_pending', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_secret_pending')
    # ### end Alembic commands ###
